name: Update Subscription

on:
  schedule:
    # 每天凌晨1:30 UTC 运行（北京时间1:30）
    - cron: '30 17 * * *'
  workflow_dispatch:
    # 允许手动触发
    inputs:
      trigger:
        description: 'Manual trigger for update'
        required: true
        default: 'true'

jobs:
  update_subscription:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up curl
      run: sudo apt-get install -y curl

    - name: Download subscription file
      run: |
        echo "Fetching subscription from the API..."
        curl -s -o Clash/config/dijia-node.list "https://sub1.114514000000.xyz/api/v1/client/subscribe?token=b1a14d4ff295e82750eaf0ebe9f70ae2"
    
    - name: Commit and push new subscription file
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Check if there's a difference
        if git diff --quiet; then
          echo "No changes detected, skipping commit."
        else
          git add Clash/config/dijia-node.list
          git commit -m "Update dijia-node.list"
          git push origin main
        fi
